development:
  adapter: postgresql
  encoding: unicode
  database: selfstarter_development
  pool: 5
  host: localhost


test:
  adapter: postgresql
  encoding: unicode
  database: selfstarter_test
  pool: 5
  host: localhost
